/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SourceCode;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;
import org.pushingpixels.substance.api.skin.GeminiSkin;

/**
 *
 * @author Hak Srun Lao
 */
public class AddCourse extends javax.swing.JFrame {
    Connection connect;
    PreparedStatement prepare;
    ResultSet result;

    /**
     * Creates new form AddCourse
     */
    public AddCourse() {
        initComponents();
        connect = Functions.connectToDatabase();
        setInitial();
    }
    
    public final void setInitial() {
        Functions.initialFrame(this);
        setTeacher();
        callCreate();
        callBack();
    }
    
    public void setTeacher() {
        String getTeacherSQL = "select RealName from Account where UserType = 'Teacher'";
        try {
            prepare = connect.prepareStatement(getTeacherSQL);
            result = prepare.executeQuery();
            while(result.next()) {
                String teacherName = result.getString("RealName");
                jComboBoxCourseTeacher.addItem(teacherName);
            }
        } catch(SQLException ex) {
            Logger.getLogger(AddCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void createFunction() {
        String createSQL = "insert into Course(CourseID, CourseName, Sections, CourseTeacher) "
                + "values(?, ?, ?, ?)";
        String courseID = jTextFieldCourseID.getText();
        String courseName = jTextFieldCourseName.getText();
        String sections = (String)jComboBoxSections.getSelectedItem();
        String courseTeacher = (String)jComboBoxCourseTeacher.getSelectedItem();
        try {
            if(courseID.equals("") || courseName.equals("") || sections.equals("") || courseTeacher.equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill all information!");
            } else {
                prepare = connect.prepareStatement(createSQL);
                prepare.setString(1, courseID);
                prepare.setString(2, courseName);
                prepare.setString(3, sections);
                prepare.setString(4, courseTeacher);
                prepare.execute();
                JOptionPane.showMessageDialog(null, "New Course added!");
                Functions.clearTextField(jPanelNewCourse);
                jComboBoxSections.setSelectedIndex(0);
                jComboBoxCourseTeacher.setSelectedIndex(0);
            }
        } catch(SQLException ex) {
            Logger.getLogger(AddCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void callCreate() {
        jButtonCreate.addActionListener((ActionEvent e) -> {
            createFunction();
        });
    }
    
    public void callBack() {
        jButtonBack.addActionListener((ActionEvent e) -> {
            Functions.gotoNewFrame(this, new HomeAdmin());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNewCourse = new javax.swing.JPanel();
        jLabelCourseID = new javax.swing.JLabel();
        jLabelCourseName = new javax.swing.JLabel();
        jLabelSections = new javax.swing.JLabel();
        jLabelCourseTeacher = new javax.swing.JLabel();
        jTextFieldCourseID = new javax.swing.JTextField();
        jTextFieldCourseName = new javax.swing.JTextField();
        jComboBoxSections = new javax.swing.JComboBox<>();
        jButtonCreate = new javax.swing.JButton();
        jComboBoxCourseTeacher = new javax.swing.JComboBox<>();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CMS - Add Course");

        jPanelNewCourse.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Course", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 24))); // NOI18N

        jLabelCourseID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCourseID.setText("Course ID");

        jLabelCourseName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCourseName.setText("Course Name");

        jLabelSections.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSections.setText("Sections");

        jLabelCourseTeacher.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCourseTeacher.setText("Course Teacher");

        jTextFieldCourseID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextFieldCourseName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jComboBoxSections.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxSections.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "2", "3" }));

        jButtonCreate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonCreate.setText("Create");

        jComboBoxCourseTeacher.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxCourseTeacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        javax.swing.GroupLayout jPanelNewCourseLayout = new javax.swing.GroupLayout(jPanelNewCourse);
        jPanelNewCourse.setLayout(jPanelNewCourseLayout);
        jPanelNewCourseLayout.setHorizontalGroup(
            jPanelNewCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNewCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNewCourseLayout.createSequentialGroup()
                        .addComponent(jLabelCourseTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCourseTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNewCourseLayout.createSequentialGroup()
                        .addComponent(jLabelSections, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSections, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNewCourseLayout.createSequentialGroup()
                        .addComponent(jLabelCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNewCourseLayout.createSequentialGroup()
                        .addComponent(jLabelCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNewCourseLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelNewCourseLayout.setVerticalGroup(
            jPanelNewCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNewCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNewCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNewCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSections, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSections, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNewCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCourseTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCourseTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanelNewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanelNewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            SubstanceLookAndFeel.setSkin(new GeminiSkin());
            new AddCourse().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JComboBox<String> jComboBoxCourseTeacher;
    private javax.swing.JComboBox<String> jComboBoxSections;
    private javax.swing.JLabel jLabelCourseID;
    private javax.swing.JLabel jLabelCourseName;
    private javax.swing.JLabel jLabelCourseTeacher;
    private javax.swing.JLabel jLabelSections;
    private javax.swing.JPanel jPanelNewCourse;
    private javax.swing.JTextField jTextFieldCourseID;
    private javax.swing.JTextField jTextFieldCourseName;
    // End of variables declaration//GEN-END:variables
}
