/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SourceCode;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;
import org.pushingpixels.substance.api.skin.GeminiSkin;

/**
 *
 * @author HSL
 */
public class EditMark extends javax.swing.JFrame {
    Connection connect;
    PreparedStatement prepare;
    ResultSet result;

    /**
     * Creates new form EditMark
     */
    public EditMark() {
        initComponents();
        connect = Functions.connectToDatabase();
        setInitial();
    }
    
    public final void setInitial() {
        Functions.initialFrame(this);
        showCourse();
        setTableModel();
        setCourseName();
        callSubmit();
        back();
    }
    
    public void setTableModel() {
        jTableResult.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 14));
        TableColumn column;
        column = jTableResult.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = jTableResult.getColumnModel().getColumn(1);
        column.setPreferredWidth(300);
        column = jTableResult.getColumnModel().getColumn(2);
        column.setPreferredWidth(100);
    }
    
    public void showCourse() {
        String showSQL = "select StudentID, StudentName, Mark from Result where CourseName = ?";
        String courseName = (String)HomeTeacher.jComboBoxShow.getSelectedItem();
        try {
            prepare = connect.prepareStatement(showSQL);
            prepare.setString(1, courseName);
            result = prepare.executeQuery();
            jTableResult.setModel(DbUtils.resultSetToTableModel(result));
        } catch(SQLException ex) {
            Logger.getLogger(HomeTeacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setCourseName() {
        String courseName = (String)HomeTeacher.jComboBoxShow.getSelectedItem();
        jLabelCourseName.setText(courseName);
    }
    
    public void submit() {
        int row = 0;
        int rowCount = jTableResult.getModel().getRowCount();
        String courseName = jLabelCourseName.getText();
        do {
            String studentID = (String)jTableResult.getModel().getValueAt(row, 0);
            String mark = (String)jTableResult.getModel().getValueAt(row, 2);
            String submitSQL = "update Result set Mark = ? where StudentID = ? and CourseName = ?";
            try {
                prepare = connect.prepareStatement(submitSQL);
                prepare.setString(1, mark);
                prepare.setString(2, studentID);
                prepare.setString(3, courseName);
                prepare.execute();
            } catch(SQLException ex) {
                Logger.getLogger(EditMark.class.getName()).log(Level.SEVERE, null, ex);
            }
            row++;
        } while(row < rowCount);
        JOptionPane.showMessageDialog(null, "Student marks edited!");
        setVisible(false);
        HomeTeacher open = new HomeTeacher();
        open.setVisible(true);
        HomeTeacher.jComboBoxShow.setSelectedItem(courseName);
    }
    public void callSubmit() {
        jButtonSubmit.addActionListener((ActionEvent e) -> {
            submit();
        });
    }
    
    public void back() {
        jButtonBack.addActionListener((ActionEvent e) -> {
            int yesOrNo = JOptionPane.showConfirmDialog(null, "Are you sure want to close Edit Mark windows?", "CMS", JOptionPane.YES_NO_OPTION);
            if(yesOrNo == 0) {
                Functions.gotoNewFrame(this, new HomeTeacher());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();
        jPanelResult = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTableResult = new javax.swing.JTable();
        jLabelCourseName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CMS - Edit Mark");

        jButtonBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonBack.setText("Back");

        jButtonSubmit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSubmit.setText("Submit");

        jPanelResult.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Mark", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 24))); // NOI18N

        jTableResult.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Mark"
            }
        ));
        jTableResult.setRowHeight(25);
        jScrollPane.setViewportView(jTableResult);

        javax.swing.GroupLayout jPanelResultLayout = new javax.swing.GroupLayout(jPanelResult);
        jPanelResult.setLayout(jPanelResultLayout);
        jPanelResultLayout.setHorizontalGroup(
            jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelResultLayout.setVerticalGroup(
            jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelCourseName.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabelCourseName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCourseName.setText("Course Name");
        jLabelCourseName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabelCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            SubstanceLookAndFeel.setSkin(new GeminiSkin());
            new EditMark().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabelCourseName;
    private javax.swing.JPanel jPanelResult;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableResult;
    // End of variables declaration//GEN-END:variables
}
