/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SourceCode;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;
import org.pushingpixels.substance.api.skin.GeminiSkin;

/**
 *
 * @author Hak Srun Lao
 */
public class HomeAdmin extends javax.swing.JFrame {
    Connection connect; 
    PreparedStatement prepare;
    ResultSet result;

    /**
     * Creates new form HomeAdmin
     */
    public HomeAdmin() {
        initComponents();
        connect = Functions.connectToDatabase();
        setInitial();
    }
    
    public final void setInitial() {
        Functions.initialFrame(this);
        setWelcome();
        Functions.addTeacher(this, jButtonTeacher);
        Functions.addStudent(this, jButtonStudent);
        Functions.addCourse(this, jButtonCourse);
        Functions.editTeacher(this, jButtonEditTeacher);
        Functions.editStudent(this, jButtonEditStudent);
        Functions.editCourse(this, jButtonEditCourse);
        Functions.logOut(this, jButtonLogOut);
        Functions.exit(jButtonExit);
        callAddAdmin();
        callEditAdmin();
    }
    
    public void setWelcome() {
        String getInfomationSQL = "select * from Account where UserName = ?";
        String userName = Login.jTextFieldUserName.getText();
        try {
            prepare = connect.prepareStatement(getInfomationSQL);
            prepare.setString(1, userName);
            result = prepare.executeQuery();
            if(result.next()) {
                String realName = result.getString("RealName");
                String userType = result.getString("userType");
                jLabelWelcome.setText("****** Welcome " + realName + " ******");
                if(userType.equals("SuperAdmin")) {
                    jButtonNewAdmin.setVisible(true);
                    jButtonEditAdmin.setVisible(true);
                } else {
                    jButtonNewAdmin.setVisible(false);
                    jButtonEditAdmin.setVisible(false);
                }
            }
        } catch(SQLException ex) {
            Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void callAddAdmin() {
        jButtonNewAdmin.addActionListener((ActionEvent e) -> {
            Functions.gotoNewFrame(this, new AddAdmin());
        });
    }
    
    public void callEditAdmin() {
        jButtonEditAdmin.addActionListener((ActionEvent e) -> {
            Functions.gotoNewFrame(this, new EditAdmin());
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcome = new javax.swing.JLabel();
        jSeparatorWelcome = new javax.swing.JSeparator();
        jPanelAddNew = new javax.swing.JPanel();
        jButtonTeacher = new javax.swing.JButton();
        jButtonStudent = new javax.swing.JButton();
        jButtonCourse = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonNewAdmin = new javax.swing.JButton();
        jPanelEdit = new javax.swing.JPanel();
        jButtonEditCourse = new javax.swing.JButton();
        jButtonEditTeacher = new javax.swing.JButton();
        jButtonEditStudent = new javax.swing.JButton();
        jButtonEditAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CMS - Admin");

        jLabelWelcome.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcome.setText("Welcome");
        jLabelWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanelAddNew.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 24))); // NOI18N

        jButtonTeacher.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Teacher.png"))); // NOI18N
        jButtonTeacher.setText("Teacher");
        jButtonTeacher.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTeacher.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonTeacher.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonStudent.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Student.png"))); // NOI18N
        jButtonStudent.setText("Student");
        jButtonStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStudent.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonCourse.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Course.png"))); // NOI18N
        jButtonCourse.setText("Course");
        jButtonCourse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCourse.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonCourse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanelAddNewLayout = new javax.swing.GroupLayout(jPanelAddNew);
        jPanelAddNew.setLayout(jPanelAddNewLayout);
        jPanelAddNewLayout.setHorizontalGroup(
            jPanelAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddNewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButtonStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButtonCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAddNewLayout.setVerticalGroup(
            jPanelAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddNewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonLogOut.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonLogOut.setText("Log Out");

        jButtonExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonExit.setText("Exit");

        jButtonNewAdmin.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonNewAdmin.setText("Add New Admin");

        jPanelEdit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 24))); // NOI18N

        jButtonEditCourse.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonEditCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Course Edit.png"))); // NOI18N
        jButtonEditCourse.setText("Course");
        jButtonEditCourse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditCourse.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonEditCourse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonEditTeacher.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonEditTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Teacher Edit.png"))); // NOI18N
        jButtonEditTeacher.setText("Teacher");
        jButtonEditTeacher.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditTeacher.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonEditTeacher.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonEditStudent.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonEditStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Student Edit.png"))); // NOI18N
        jButtonEditStudent.setText("Student");
        jButtonEditStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditStudent.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonEditStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanelEditLayout = new javax.swing.GroupLayout(jPanelEdit);
        jPanelEdit.setLayout(jPanelEditLayout);
        jPanelEditLayout.setHorizontalGroup(
            jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEditTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButtonEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButtonEditCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelEditLayout.setVerticalGroup(
            jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonEditAdmin.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonEditAdmin.setText("Edit Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparatorWelcome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 30, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanelAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            SubstanceLookAndFeel.setSkin(new GeminiSkin());
            new HomeAdmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCourse;
    private javax.swing.JButton jButtonEditAdmin;
    private javax.swing.JButton jButtonEditCourse;
    private javax.swing.JButton jButtonEditStudent;
    private javax.swing.JButton jButtonEditTeacher;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonNewAdmin;
    private javax.swing.JButton jButtonStudent;
    private javax.swing.JButton jButtonTeacher;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanelAddNew;
    private javax.swing.JPanel jPanelEdit;
    private javax.swing.JSeparator jSeparatorWelcome;
    // End of variables declaration//GEN-END:variables
}
