/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SourceCode;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;
import org.pushingpixels.substance.api.skin.GeminiSkin;

/**
 *
 * @author Hak Srun Lao
 */
public class HomeTeacher extends javax.swing.JFrame {
    Connection connect;
    PreparedStatement prepare;
    ResultSet result;
    String realName;

    /**
     * Creates new form HomeTeacher
     */
    public HomeTeacher() {
        initComponents();
        connect = Functions.connectToDatabase();
        setInitial();
    }
    
    public final void setInitial() {
        Functions.initialFrame(this);
        setWelcome();
        addCourse();
        setTableModel();
        Functions.logOut(this, jButtonLogOut);
        showToTable();
        editMark();
    }
    
    public void setWelcome() {
        String getRealNameSQL = "select RealName from Account where UserName = ?";
        String userName = Login.jTextFieldUserName.getText();
        try {
            prepare = connect.prepareStatement(getRealNameSQL);
            prepare.setString(1, userName);
            result = prepare.executeQuery();
            if(result.next()) {
                realName = result.getString("RealName");
                jLabelWelcome.setText("****** Welcome " + realName + " ******");
            }
        } catch(SQLException ex) {
            Logger.getLogger(HomeTeacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setTableModel() {
        jTableResult.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 14));
        TableColumn column;
        column = jTableResult.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = jTableResult.getColumnModel().getColumn(1);
        column.setPreferredWidth(300);
        column = jTableResult.getColumnModel().getColumn(2);
        column.setPreferredWidth(100);
    }
    
    public void addCourse() {
        String addSQL = "select CourseName from Course where CourseTeacher = ?";
        try {
            prepare = connect.prepareStatement(addSQL);
            prepare.setString(1, realName);
            result = prepare.executeQuery();
            while(result.next()) {
                String courseName = result.getString("CourseName");
                jComboBoxShow.addItem(courseName);
            }
        } catch(SQLException ex) {
            Logger.getLogger(HomeTeacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void showCourse() {
        String showSQL = "select StudentID, StudentName, Mark from Result where CourseName = ?";
        String courseName = (String)jComboBoxShow.getSelectedItem();
        try {
            prepare = connect.prepareStatement(showSQL);
            prepare.setString(1, courseName);
            result = prepare.executeQuery();
            jTableResult.setModel(DbUtils.resultSetToTableModel(result));
        } catch(SQLException ex) {
            Logger.getLogger(HomeTeacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void showToTable() {
        jComboBoxShow.addActionListener((ActionEvent e) -> {
            showCourse();
            setTableModel();
        });
    }
    
    public void editMark() {
        jButtonEditMark.addActionListener((ActionEvent e) -> {
            Functions.gotoNewFrame(this, new EditMark());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcome = new javax.swing.JLabel();
        jSeparatorWelcome = new javax.swing.JSeparator();
        jLabelShow = new javax.swing.JLabel();
        jComboBoxShow = new javax.swing.JComboBox<>();
        jScrollPane = new javax.swing.JScrollPane();
        jTableResult = new javax.swing.JTable();
        jButtonLogOut = new javax.swing.JButton();
        jButtonEditMark = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CMS - Teacher");

        jLabelWelcome.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcome.setText("Welcome");
        jLabelWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelShow.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelShow.setText("Please select a course to show:");

        jComboBoxShow.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxShow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jTableResult.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Mark"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableResult.setRowHeight(25);
        jScrollPane.setViewportView(jTableResult);

        jButtonLogOut.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonLogOut.setText("Log Out");

        jButtonEditMark.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonEditMark.setText("Edit Mark");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparatorWelcome)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEditMark, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelShow, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxShow, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelShow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxShow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditMark, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            SubstanceLookAndFeel.setSkin(new GeminiSkin());
            new HomeTeacher().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditMark;
    private javax.swing.JButton jButtonLogOut;
    public static javax.swing.JComboBox<String> jComboBoxShow;
    private javax.swing.JLabel jLabelShow;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparatorWelcome;
    private javax.swing.JTable jTableResult;
    // End of variables declaration//GEN-END:variables
}
